name: flutter_ble_uart
description: Package to easily integrate UART over Bluetooth Low Energy into your Flutter app
version: 0.0.2
homepage: https://github.com/itavero/flutter-ble-uart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
